apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
      protocol: TCP
    - name: https
      targetPort: 443
      port: 443
      protocol: TCP
  selector:
    {{- include "chart.selector" . | nindent 4 }}
